[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9.6"
  DJANGO_SETTINGS_MODULE = "config.settings_production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["requirements.txt", "manage.py", "config/**", "main/**"]
  node_bundler = "esbuild" 